name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    
  build:
    runs-on: ubuntu-latest
    env:
      keylink:  ${{ secrets.KEYLINK }}
      hostname: ${{ secrets.HOSTNAME }}
      ssh_port: ${{ secrets.SSH_PORT }}
      appsettings: ${{ secrets.APPSETTINGS }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore --configuration Release
    - name: Generate Bundle
      run: |
        mkdir VecoBackend/VecoBackend
        rm -rf VecoBackend/bin/Release/net6.0/VecoBackend
        echo $appsettings > VecoBackend/VecoBackend/appsettings.json
        dotnet tool install --global dotnet-ef
        dotnet ef migrations bundle --project VecoBackend/ -r linux-x64 --verbose
        
    - name: Download SSH key
      run: wget -O k.key "$keylink";chmod 400 k.key
    - name: Launch migrations
      run: ssh -i k.key -o StrictHostKeyChecking=no deploy@$hostname -p $ssh_port "chmod +x ~/app/bundle; exec ~/app/bundle"
    - name: Upload artifacts
      run:  rsync -ratlz --rsh="ssh -i k.key -o StrictHostKeyChecking=no -l deploy -p $ssh_port" bin/Release/net6.0/publish/ deploy@$hostname:/home/deploy/app/
